"""init

Revision ID: 5aa2825e6f42
Revises: 
Create Date: 2026-07-18 07:41:55.307654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa2825e6f42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cultures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('categorie_agronomique', sa.String(length=80), nullable=False),
    sa.Column('couleur', sa.String(length=9), nullable=False),
    sa.Column('rendement_reference_kg_ha', sa.Float(), nullable=False),
    sa.Column('cycle_jours', sa.Integer(), nullable=True),
    sa.Column('sols_favorables', sa.String(length=200), nullable=False),
    sa.Column('saison_favorable', sa.String(length=40), nullable=False),
    sa.Column('tolerance_secheresse', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('marches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('ville', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('ville', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('agriculteur_depuis', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('alertes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('culture_id', sa.Integer(), nullable=True),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('titre', sa.String(length=180), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('couleur', sa.String(length=9), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['culture_id'], ['cultures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcelles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('culture_id', sa.Integer(), nullable=False),
    sa.Column('superficie_ha', sa.Float(), nullable=False),
    sa.Column('type_sol', sa.String(length=80), nullable=True),
    sa.Column('statut', sa.String(length=40), nullable=False),
    sa.Column('date_plantation', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['culture_id'], ['cultures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prix_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('culture_id', sa.Integer(), nullable=False),
    sa.Column('marche_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('prix_fcfa_kg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['culture_id'], ['cultures.id'], ),
    sa.ForeignKeyConstraint(['marche_id'], ['marches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prix_records', schema=None) as batch_op:
        batch_op.create_index('ix_prix_culture_marche_date', ['culture_id', 'marche_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_prix_records_date'), ['date'], unique=False)

    op.create_table('rendement_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('culture_id', sa.Integer(), nullable=False),
    sa.Column('superficie_ha', sa.Float(), nullable=False),
    sa.Column('type_sol', sa.String(length=80), nullable=False),
    sa.Column('saison', sa.String(length=40), nullable=False),
    sa.Column('pluviometrie', sa.String(length=20), nullable=False),
    sa.Column('rendement_estime_kg_ha', sa.Float(), nullable=False),
    sa.Column('production_totale_kg', sa.Float(), nullable=False),
    sa.Column('revenu_estime_fcfa', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['culture_id'], ['cultures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rendement_predictions')
    with op.batch_alter_table('prix_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prix_records_date'))
        batch_op.drop_index('ix_prix_culture_marche_date')

    op.drop_table('prix_records')
    op.drop_table('parcelles')
    op.drop_table('alertes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('marches')
    op.drop_table('cultures')
    # ### end Alembic commands ###
